### ISSUE TITLE
weekly error

### ISSUE THREAD

**Issue by Agamemnon128** [mikepauer/Carbonite.Weekly#3]
Message: Interface/AddOns/Carbonite.Weekly/NxWeekly.lua:701: attempt to call global 'IsQuestFlaggedCompleted' (a nil value)
Time: Wed Dec  7 13:12:26 2022
Count: 1
Stack: Interface/AddOns/Carbonite.Weekly/NxWeekly.lua:701: attempt to call global 'IsQuestFlaggedCompleted' (a nil value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: in function `IsQuestFlaggedCompleted'
[string "@Interface/AddOns/Carbonite.Weekly/NxWeekly.lua"]:701: in function `CharRecord'
[string "@Interface/AddOns/Carbonite.Weekly/NxWeekly.lua"]:635: in function `Login'
[string "@Interface/AddOns/Carbonite.Weekly/NxWeekly.lua"]:570: in function `func'
[string "@Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua"]:57: in function <Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

**Comment by IrcDirk** [comment]
Please update to Alpha or from this repo 701 is not ``IsQuestFlaggedCompleted``
